# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('cover_id', models.CharField(max_length=200)),
                ('publish_time', models.IntegerField(default=0)),
                ('insert_time', models.IntegerField(default=0)),
                ('page_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_id', models.CharField(max_length=200)),
                ('image_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_id', models.CharField(max_length=200)),
                ('desc', models.CharField(default=b'', max_length=200)),
            ],
        ),
    ]
