# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image_id',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
