# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_auto_20170611_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='all_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='insert_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='publish_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
