# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_auto_20170611_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
