# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
