# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_auto_20170628_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
