# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_auto_20170628_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.CharField(default=b'', max_length=1024),
        ),
    ]
