# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_auto_20170611_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
