# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_auto_20170628_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
