# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_gallery_cover_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_id', models.CharField(max_length=200)),
            ],
        ),
    ]
